name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: xcodebuild -project OpenTweet.xcodeproj -scheme OpenTweetTests build-for-testing
      - name: Test
        run: xcodebuild -project OpenTweet.xcodeproj -scheme OpenTweetTests -destination 'platform=iOS Simulator,name=Any iOS Device' test
      - name: Test UI
        run: xcodebuild -project OpenTweet.xcodeproj -scheme OpenTweetUITests -destination 'platform=iOS Simulator,name=Any iOS Device' test
