name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Select Xcode
        run: sudo Xcode-select -switch /Applications/Xcode_15.0.1.app
      - name: Build
        run: xcodebuild -project OpenTweet.xcodeproj -scheme OpenTweetTests build-for-testing -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17'
      - name: Test
        run: xcodebuild -project OpenTweet.xcodeproj -scheme OpenTweetTests -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17'
      - name: Test UI
        run: xcodebuild -project OpenTweet.xcodeproj -scheme OpenTweetUITests -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17'
